import { pgTable, text, serial, timestamp, integer, boolean } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// Categories Table
export const categories = pgTable("categories", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
});

// Stories Table
export const stories = pgTable("stories", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  slug: text("slug").unique().notNull(),
  content: text("content").notNull(), // Long story content
  preview: text("preview").notNull(), // Snippet for guests
  categoryId: integer("category_id").references(() => categories.id),
  status: text("status").default("draft"), // draft, published
  thumbnailUrl: text("thumbnail_url"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// BetterAuth Tables (Basic schema for reference, usually generated by their CLI/Plugin)
export const user = pgTable("user", {
	id: text("id").primaryKey(),
	name: text("name").notNull(),
	email: text("email").notNull().unique(),
	emailVerified: boolean("emailVerified").notNull(),
	image: text("image"),
	createdAt: timestamp("createdAt").notNull(),
	updatedAt: timestamp("updatedAt").notNull(),
});

export const session = pgTable("session", {
	id: text("id").primaryKey(),
	expiresAt: timestamp("expiresAt").notNull(),
	token: text("token").notNull().unique(),
	createdAt: timestamp("createdAt").notNull(),
	updatedAt: timestamp("updatedAt").notNull(),
	ipAddress: text("ipAddress"),
	userAgent: text("userAgent"),
	userId: text("userId").notNull().references(() => user.id)
});

export const account = pgTable("account", {
	id: text("id").primaryKey(),
	accountId: text("accountId").notNull(),
	providerId: text("providerId").notNull(),
	userId: text("userId").notNull().references(() => user.id),
	accessToken: text("accessToken"),
	refreshToken: text("refreshToken"),
	idToken: text("idToken"),
	accessTokenExpiresAt: timestamp("accessTokenExpiresAt"),
	refreshTokenExpiresAt: timestamp("refreshTokenExpiresAt"),
	scope: text("scope"),
	password: text("password"),
	createdAt: timestamp("createdAt").notNull(),
	updatedAt: timestamp("updatedAt").notNull(),
});

export const verification = pgTable("verification", {
	id: text("id").primaryKey(),
	identifier: text("identifier").notNull(),
	value: text("value").notNull(),
	expiresAt: timestamp("expiresAt").notNull(),
	createdAt: timestamp("createdAt").notNull(),
	updatedAt: timestamp("updatedAt").notNull(),
});

// Heroes Table (User Roles/Stats)
export const heroes = pgTable("heroes", {
  id: serial("id").primaryKey(),
  userId: text("userId").notNull().references(() => user.id).unique(),
  role: text("role").default("default"), // dwarf, peri, kesatria, penyihir, pemanah
  xp: integer("xp").default(0).notNull(),
  level: integer("level").default(1).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Quests Table
export const quests = pgTable("quests", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  description: text("description"),
  xpReward: integer("xp_reward").notNull(),
  type: text("type").notNull(), // READING, VOCABULARY, etc.
  targetValue: integer("target_value").notNull(),
  isDaily: boolean("is_daily").default(true).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// User Quest Progress Table
export const userQuests = pgTable("user_quests", {
  id: serial("id").primaryKey(),
  userId: text("user_id").notNull().references(() => user.id),
  questId: integer("quest_id").notNull().references(() => quests.id),
  currentValue: integer("current_value").default(0).notNull(),
  isCompleted: boolean("is_completed").default(false).notNull(),
  lastUpdated: timestamp("last_updated").defaultNow().notNull(),
  completedAt: timestamp("completed_at"),
});

// Reading Progress Table
export const readingProgress = pgTable("reading_progress", {
  id: serial("id").primaryKey(),
  userId: text("user_id").notNull().references(() => user.id),
  storyId: integer("story_id").notNull().references(() => stories.id),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Relations
export const categoriesRelations = relations(categories, ({ many }) => ({
  stories: many(stories),
}));

export const heroesRelations = relations(heroes, ({ one }) => ({
  user: one(user, {
    fields: [heroes.userId],
    references: [user.id],
  }),
}));

export const readingProgressRelations = relations(readingProgress, ({ one }) => ({
  user: one(user, {
    fields: [readingProgress.userId],
    references: [user.id],
  }),
  story: one(stories, {
    fields: [readingProgress.storyId],
    references: [stories.id],
  }),
}));

// Story Pages Table
export const storyPages = pgTable("story_pages", {
  id: serial("id").primaryKey(),
  storyId: integer("story_id").notNull().references(() => stories.id),
  pageNumber: integer("page_number").notNull(),
  content: text("content").notNull(),
  imageUrl: text("image_url"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Story Pins Table (User's last position in a story)
export const storyPins = pgTable("story_pins", {
  id: serial("id").primaryKey(),
  userId: text("user_id").notNull().references(() => user.id),
  storyId: integer("story_id").notNull().references(() => stories.id),
  pageNumber: integer("page_number").notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Story Page Favorites (Multiple pages can be favorited)
export const storyPageFavorites = pgTable("story_page_favorites", {
  id: serial("id").primaryKey(),
  userId: text("user_id").notNull().references(() => user.id),
  storyId: integer("story_id").notNull().references(() => stories.id),
  pageNumber: integer("page_number").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// New Relations
export const storyPagesRelations = relations(storyPages, ({ one }) => ({
  story: one(stories, {
    fields: [storyPages.storyId],
    references: [stories.id],
  }),
}));

export const storyPinsRelations = relations(storyPins, ({ one }) => ({
  user: one(user, {
    fields: [storyPins.userId],
    references: [user.id],
  }),
  story: one(stories, {
    fields: [storyPins.storyId],
    references: [stories.id],
  }),
}));

export const storyPageFavoritesRelations = relations(storyPageFavorites, ({ one }) => ({
  user: one(user, {
    fields: [storyPageFavorites.userId],
    references: [user.id],
  }),
  story: one(stories, {
    fields: [storyPageFavorites.storyId],
    references: [stories.id],
  }),
}));

export const storiesRelations = relations(stories, ({ one, many }) => ({
  category: one(categories, {
    fields: [stories.categoryId],
    references: [categories.id],
  }),
  pages: many(storyPages),
}));

export const questsRelations = relations(quests, ({ many }) => ({
  userQuests: many(userQuests),
}));

export const userQuestsRelations = relations(userQuests, ({ one }) => ({
  user: one(user, {
    fields: [userQuests.userId],
    references: [user.id],
  }),
  quest: one(quests, {
    fields: [userQuests.questId],
    references: [quests.id],
  }),
}));

